#!/bin/bash
echo "=========================================="
echo "  Opening Your Portfolio"
echo "=========================================="
echo ""
echo "Your portfolio HTML files are located at:"
echo "/tmp/cc-agent/57918838/project/public/"
echo ""
echo "To view them, run ONE of these commands:"
echo ""
echo "1. Using npx serve (recommended):"
echo "   cd /tmp/cc-agent/57918838/project/public"
echo "   npx serve -p 8000"
echo ""
echo "2. Using Python:"
echo "   cd /tmp/cc-agent/57918838/project/public"
echo "   python3 -m http.server 8000"
echo ""
echo "3. Open directly in browser:"
echo "   file:///tmp/cc-agent/57918838/project/public/index.html"
echo ""
echo "=========================================="
